# Generated by Django 3.0.5 on 2020-10-21 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('orderItemCode', models.CharField(blank=True, max_length=100, verbose_name='Codigo de Item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(blank=True, max_length=300, verbose_name='Usuario Administrador')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('discountCode', models.CharField(blank=True, max_length=100, verbose_name='Codigo de Descuento')),
                ('orderCode', models.CharField(blank=True, max_length=300, verbose_name='Codigo de Pedido')),
                ('status', models.TextField(blank=True, choices=[('NoPagados', 'NoPagados'), ('Procesando', 'Procesando'), ('Realizado', 'Realizado'), ('Revision', 'Revision'), ('Enviado', 'Enviado'), ('Pagado', 'Pagado'), ('Comentado', 'Comentado'), ('Devuelto', 'Devuelto')], default='NoPagados', max_length=50, verbose_name='Estado')),
                ('orderLocation', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección de Envío')),
                ('payMethod', models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta de Crédito/Débito'), ('PayPal', 'PayPal'), ('Extra', 'Extra Financiamiento'), ('Link', 'Link'), ('Deposito', 'Deposito Bancario')], default='Efectivo', max_length=500, null=True, verbose_name='Metodo de Pago')),
                ('paystaus', models.TextField(blank=True, choices=[('NoPagados', 'NoPagados'), ('Procesando', 'Procesando'), ('Pagado', 'Pagado')], default='NoPagados', max_length=50, verbose_name='Estado de Pago')),
                ('items', models.ManyToManyField(to='cart.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
