# Generated by Django 3.0.5 on 2020-08-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderCode',
            field=models.CharField(blank=True, max_length=300, verbose_name='Codigo de Pedido'),
        ),
    ]
