# Generated by Django 3.0.5 on 2020-08-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_ordercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='orderItemCode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Codigo de Item'),
        ),
    ]
