# Generated by Django 3.0.5 on 2020-08-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orderitem_orderitemcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(blank=True, choices=[('NoPagados', 'NoPagados'), ('Procesando', 'Procesando'), ('Enviado', 'Enviado'), ('Pagado', 'Pagado'), ('Comentado', 'Comentado'), ('Devuelto', 'Devuelto')], default='NoPagados', max_length=50, verbose_name='Estado'),
        ),
    ]
