# Generated by Django 3.0.5 on 2020-09-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderLocation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección de Envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='payMethod',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('PayPal', 'PayPal'), ('Link', 'Link'), ('Deposito', 'Deposito')], default='Efectivo', max_length=500, null=True, verbose_name='Metodo de Pago'),
        ),
        migrations.AddField(
            model_name='order',
            name='paystaus',
            field=models.TextField(blank=True, choices=[('NoPagados', 'NoPagados'), ('Procesando', 'Procesando'), ('Pagado', 'Pagado')], default='NoPagados', max_length=50, verbose_name='Estado de Pago'),
        ),
    ]
