# Generated by Django 3.0.5 on 2020-09-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200907_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discountCode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Codigo de Descuento'),
        ),
    ]
