# Generated by Django 3.0.5 on 2020-10-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20201018_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payMethod',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta de Crédito/Débito'), ('PayPal', 'PayPal'), ('Extra', 'Extra Financiamiento'), ('Link', 'Link'), ('Deposito', 'Deposito Bancario')], default='Efectivo', max_length=500, null=True, verbose_name='Metodo de Pago'),
        ),
    ]
