# Generated by Django 3.0.5 on 2020-10-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20201018_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin',
            field=models.CharField(blank=True, max_length=300, verbose_name='Usuario Administrador'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(blank=True, choices=[('NoPagados', 'NoPagados'), ('Procesando', 'Procesando'), ('Revision', 'Revision'), ('Enviado', 'Enviado'), ('Pagado', 'Pagado'), ('Comentado', 'Comentado'), ('Devuelto', 'Devuelto')], default='NoPagados', max_length=50, verbose_name='Estado'),
        ),
    ]
