# Generated by Django 3.0.5 on 2020-10-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20201020_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(blank=True, choices=[('NoPagados', 'NoPagados'), ('Procesando', 'Procesando'), ('Realizado', 'Realizado'), ('Revision', 'Revision'), ('Enviado', 'Enviado'), ('Pagado', 'Pagado'), ('Comentado', 'Comentado'), ('Devuelto', 'Devuelto')], default='NoPagados', max_length=50, verbose_name='Estado'),
        ),
    ]
