# Generated by Django 3.0.5 on 2020-04-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=400, verbose_name='Direccion')),
                ('logo', models.ImageField(blank=True, upload_to='Services', verbose_name='Logo')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, verbose_name='Youtube')),
                ('website', models.URLField(blank=True, verbose_name='WebSite')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefono')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('resume', models.TextField(blank=True, verbose_name='Resumen')),
            ],
        ),
    ]
