# Generated by Django 3.0.5 on 2020-10-21 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Categoria')),
                ('icono', models.ImageField(blank=True, upload_to='Category', verbose_name='Icono')),
                ('categoryCode', models.CharField(blank=True, max_length=1, verbose_name='Codigo Categoría')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('commission', models.IntegerField(blank=True, default=0, verbose_name='Comisión')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('color', models.CharField(max_length=10, verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=400, verbose_name='Direccion')),
                ('logo', models.ImageField(blank=True, upload_to='Company', verbose_name='Logo')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, verbose_name='Youtube')),
                ('website', models.URLField(blank=True, verbose_name='WebSite')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefono')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('resume', models.TextField(blank=True, verbose_name='Resumen')),
                ('plan', models.TextField(blank=True, choices=[('Vendedor', 'Vendedor'), ('Empresario', 'Empresario'), ('Franquiciador', 'Franquiciador')], default='Vendedor', max_length=50, verbose_name='Plan')),
                ('delivery', models.BooleanField(default=True, verbose_name='Nuestro Delivery')),
                ('phoneDelivery', models.CharField(blank=True, max_length=15, verbose_name='Telefono de Delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Talla')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sub Categoria')),
                ('icono', models.ImageField(blank=True, upload_to='SubCategory', verbose_name='Icono')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Codigo de Registro')),
                ('associated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=900, verbose_name='Titulo')),
                ('resume', models.TextField(blank=True, verbose_name='Descripcion')),
                ('imagef', models.ImageField(upload_to='Product', verbose_name='Imagen Principal')),
                ('images', models.ImageField(blank=True, upload_to='Product', verbose_name='Imagen 2')),
                ('imaget', models.ImageField(blank=True, upload_to='Product', verbose_name='Imagen 3')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('priceAnchor', models.FloatField(blank=True, null=True, verbose_name='Precio Anclaje')),
                ('pricePromo', models.FloatField(blank=True, null=True, verbose_name='Precio Promocion')),
                ('promotion', models.BooleanField(default=False, verbose_name='Promocion')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('exhausted', models.BooleanField(default=False, verbose_name='Agotado')),
                ('season', models.BooleanField(default=False, verbose_name='Temporada')),
                ('virus', models.BooleanField(default=False, verbose_name='Virus')),
                ('calification', models.IntegerField(blank=True, default=0, verbose_name='Calificacion')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('productCode', models.CharField(blank=True, max_length=100, verbose_name='Codigo de Producto')),
                ('statusproduct', models.TextField(choices=[('Nuevo', 'Nuevo'), ('Casi Nuevo', 'Casi Nuevo'), ('Usado', 'Usado')], default='Nuevo', verbose_name='Estado del Producto')),
                ('warranty', models.TextField(choices=[('1', 'No Aplica'), ('2', '24 Horas'), ('3', '15 Días'), ('4', '1 Meses'), ('5', '3 Meses'), ('6', '6 Meses'), ('7', '1 Año')], default='1', verbose_name='Garantía')),
                ('original', models.TextField(choices=[('1', 'Original'), ('2', 'Réplica'), ('3', 'Copia'), ('4', 'Imitación')], default='1', verbose_name='Estatus')),
                ('views', models.PositiveIntegerField(default=0)),
                ('colors', models.ManyToManyField(blank=True, to='product.Color')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Company')),
                ('sizes', models.ManyToManyField(blank=True, to='product.Size')),
                ('subCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.SubCategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Codigo de Descuento')),
                ('typediscount', models.TextField(choices=[('Procentaje', 'Procentaje'), ('Fijo', 'Fijo')], default='Procentaje', verbose_name='Tipo de Descuento')),
                ('discount', models.IntegerField(default=1, verbose_name='Descuento')),
                ('associated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('calification', models.TextField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, verbose_name='Calificacion')),
                ('imagef', models.ImageField(blank=True, upload_to='Comment', verbose_name='Imagen 1')),
                ('images', models.ImageField(blank=True, upload_to='Comment', verbose_name='Imagen 2')),
                ('imaget', models.ImageField(blank=True, upload_to='Comment', verbose_name='Imagen 3')),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
