# Generated by Django 3.0.5 on 2020-10-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='comissionPriceProd',
            field=models.FloatField(blank=True, null=True, verbose_name='Comisión'),
        ),
    ]
