# Generated by Django 3.0.5 on 2020-04-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='available',
            field=models.BooleanField(blank=True, default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='products',
            name='exhausted',
            field=models.BooleanField(blank=True, default=False, verbose_name='Agotado'),
        ),
        migrations.AlterField(
            model_name='products',
            name='promotion',
            field=models.BooleanField(blank=True, default=False, verbose_name='Promocion'),
        ),
        migrations.AlterField(
            model_name='products',
            name='season',
            field=models.BooleanField(blank=True, default=False, verbose_name='Temporada'),
        ),
        migrations.AlterField(
            model_name='products',
            name='virus',
            field=models.BooleanField(blank=True, default=False, verbose_name='Virus'),
        ),
    ]
