# Generated by Django 3.0.5 on 2020-04-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
