# Generated by Django 3.0.5 on 2020-04-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='products',
            name='priceAnchor',
            field=models.FloatField(blank=True, verbose_name='Precio Anclaje'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pricePromo',
            field=models.FloatField(blank=True, verbose_name='Precio Promocion'),
        ),
    ]
