# Generated by Django 3.0.5 on 2020-04-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200417_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='priceAnchor',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio Anclaje'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pricePromo',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio Promocion'),
        ),
    ]
