# Generated by Django 3.0.5 on 2020-04-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200424_0737'),
    ]

    operations = [
    ]
