# Generated by Django 3.0.5 on 2020-04-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200408_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='imagef',
            field=models.ImageField(blank=True, upload_to='product/% Y/% m/% d/', verbose_name='Imagen 1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ImageField(blank=True, upload_to='product/% Y/% m/% d/', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='imaget',
            field=models.ImageField(blank=True, upload_to='product/% Y/% m/% d/', verbose_name='Imagen 3'),
        ),
    ]
