# Generated by Django 3.0.5 on 2020-04-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200417_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='season',
            field=models.BooleanField(default=False, verbose_name='Temporada'),
        ),
    ]
