# Generated by Django 3.0.5 on 2020-04-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200409_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icono',
            field=models.ImageField(blank=True, upload_to='category/%Y/%m/%d/', verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company/%Y/%m/%d/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='products',
            name='imagef',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Imagen 1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='imaget',
            field=models.ImageField(blank=True, upload_to='product/%Y/%m/%d/', verbose_name='Imagen 3'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icono',
            field=models.ImageField(blank=True, upload_to='subcategory/%Y/%m/%d/', verbose_name='Icono'),
        ),
    ]
