# Generated by Django 3.0.5 on 2020-04-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_products_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='virus',
            field=models.BooleanField(default=False, verbose_name='Virus'),
        ),
    ]
