# Generated by Django 3.0.5 on 2020-05-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200501_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='imagef',
            field=models.ImageField(upload_to='Product', verbose_name='Imagen 1'),
        ),
    ]
