# Generated by Django 3.0.5 on 2020-05-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200502_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='imagef',
            field=models.ImageField(upload_to='Product', verbose_name='Imagen Principal'),
        ),
    ]
