# Generated by Django 3.0.5 on 2020-05-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200508_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Company'),
        ),
    ]
