# Generated by Django 3.0.5 on 2020-04-10 17:28

import applications.product.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200410_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icono',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media//', location='C:\\Users\\reykr\\My Documents\\backend\\vendoapp\\vendoencasa\\media/'), upload_to=applications.product.models.category_image, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media//', location='C:\\Users\\reykr\\My Documents\\backend\\vendoapp\\vendoencasa\\media/'), upload_to=applications.product.models.company_image, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='products',
            name='imagef',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media//', location='C:\\Users\\reykr\\My Documents\\backend\\vendoapp\\vendoencasa\\media/'), upload_to=applications.product.models.product_image, verbose_name='Imagen 1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='images',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media//', location='C:\\Users\\reykr\\My Documents\\backend\\vendoapp\\vendoencasa\\media/'), upload_to=applications.product.models.product_image, verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='imaget',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media//', location='C:\\Users\\reykr\\My Documents\\backend\\vendoapp\\vendoencasa\\media/'), upload_to=applications.product.models.product_image, verbose_name='Imagen 3'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='icono',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media//', location='C:\\Users\\reykr\\My Documents\\backend\\vendoapp\\vendoencasa\\media/'), upload_to=applications.product.models.subCategory_image, verbose_name='Icono'),
        ),
    ]
