# Generated by Django 3.0.5 on 2020-04-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200410_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='delivery',
            field=models.BooleanField(default=True, verbose_name='Nuestro Delivery'),
        ),
        migrations.AddField(
            model_name='company',
            name='phoneDelivery',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefono de Delivery'),
        ),
    ]
