# Generated by Django 3.0.5 on 2020-05-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200510_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='plan',
            field=models.TextField(blank=True, choices=[('Vendedor', 'Vendedor'), ('Empresario', 'Empresario'), ('Franquiciador', 'Franquiciador')], default='Vendedor', max_length=50, verbose_name='Plan'),
        ),
    ]
