# Generated by Django 3.0.5 on 2020-08-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200526_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryCode',
            field=models.CharField(blank=True, max_length=1, verbose_name='Codigo Categoría'),
        ),
    ]
