# Generated by Django 3.0.5 on 2020-08-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_category_categorycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productCode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Codigo de Producto'),
        ),
    ]
