# Generated by Django 3.0.5 on 2020-08-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='calification',
            field=models.TextField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, verbose_name='Calificacion'),
        ),
    ]
