# Generated by Django 3.0.5 on 2020-08-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated', models.CharField(blank=True, max_length=300, verbose_name='Asociado')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Codigo de Descuento')),
                ('typediscount', models.TextField(choices=[('Procentaje', 'Procentaje'), ('Fijo', 'Fijo')], default='Procentaje', verbose_name='Tipo de Descuento')),
                ('discount', models.IntegerField(default=1, verbose_name='Descuento')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated', models.CharField(blank=True, max_length=300, verbose_name='Asociado')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Codigo de Registro')),
            ],
        ),
    ]
