# Generated by Django 3.0.5 on 2020-08-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20200828_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Codigo de Descuento'),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Codigo de Registro'),
        ),
    ]
