# Generated by Django 3.0.5 on 2020-09-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20200828_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='statusproduct',
            field=models.TextField(choices=[('Nuevo', 'Nuevo'), ('Casi Nuevo', 'Casi Nuevo'), ('Usado', 'Usado')], default='Nuevo', verbose_name='Estado del Producto'),
        ),
    ]
