# Generated by Django 3.0.5 on 2020-09-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_products_statusproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=900, verbose_name='Titulo'),
        ),
    ]
