# Generated by Django 3.0.5 on 2020-09-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20200922_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='commission',
            field=models.IntegerField(blank=True, default=0, verbose_name='Comisión'),
        ),
    ]
