# Generated by Django 3.0.5 on 2020-09-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_category_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
