# Generated by Django 3.0.5 on 2020-10-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_products_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='original',
            field=models.TextField(choices=[('1', 'Original'), ('2', 'Réplica'), ('3', 'Copia'), ('4', 'Imitación')], default='1', verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='products',
            name='warranty',
            field=models.TextField(choices=[('1', 'No Aplica'), ('2', '24 hrs'), ('3', '15 Días'), ('4', '1 Mes'), ('5', '3 Mes'), ('6', '6 Mes'), ('7', '1 Año')], default='1', verbose_name='Garantía'),
        ),
    ]
