# Generated by Django 3.0.5 on 2020-10-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20201013_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='warranty',
            field=models.TextField(choices=[('1', 'No Aplica'), ('2', '24 Horas'), ('3', '15 Días'), ('4', '1 Meses'), ('5', '3 Meses'), ('6', '6 Meses'), ('7', '1 Año')], default='1', verbose_name='Garantía'),
        ),
    ]
