# Generated by Django 3.0.5 on 2020-05-08 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField(blank=True, choices=[('Feminimo', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], max_length=500, null=True, verbose_name='Genero')),
                ('location', models.CharField(blank=True, max_length=400, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nombre Empresa')),
                ('logo', models.ImageField(blank=True, upload_to='Company', verbose_name='Logo')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('resume', models.TextField(blank=True, verbose_name='Descripción Empresa')),
                ('plan', models.BooleanField(default=False, verbose_name='Premium')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
