# Generated by Django 3.0.5 on 2020-10-21 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.TextField(blank=True, choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], max_length=500, null=True, verbose_name='Genero')),
                ('Department', models.CharField(blank=True, choices=[('Atlántida', 'Atlántida'), ('Colón', 'Colón'), ('Comayagua', 'Comayagua'), ('Copán', 'Copán'), ('Cortés', 'Cortés'), ('Choluteca', 'Choluteca'), ('El Paraíso', 'El Paraíso'), ('Francisco Morazán', 'Francisco Morazán'), ('Gracias a Dios', 'Gracias a Dios'), ('Intibucá', 'Intibucá'), ('Islas de la Bahía', 'Islas de la Bahía'), ('La Paz', 'La Paz'), ('Lempira', 'Lempira'), ('Ocotepeque', 'Ocotepeque'), ('Olancho', 'Olancho'), ('Santa Bárbara', 'Santa Bárbara'), ('Valle', 'Valle'), ('Yoro', 'Yoro')], default='Francisco Morazán', max_length=500, null=True, verbose_name='Departamento #1')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección Detallada #1')),
                ('Departments', models.CharField(blank=True, choices=[('Atlántida', 'Atlántida'), ('Colón', 'Colón'), ('Comayagua', 'Comayagua'), ('Copán', 'Copán'), ('Cortés', 'Cortés'), ('Choluteca', 'Choluteca'), ('El Paraíso', 'El Paraíso'), ('Francisco Morazán', 'Francisco Morazán'), ('Gracias a Dios', 'Gracias a Dios'), ('Intibucá', 'Intibucá'), ('Islas de la Bahía', 'Islas de la Bahía'), ('La Paz', 'La Paz'), ('Lempira', 'Lempira'), ('Ocotepeque', 'Ocotepeque'), ('Olancho', 'Olancho'), ('Santa Bárbara', 'Santa Bárbara'), ('Valle', 'Valle'), ('Yoro', 'Yoro')], default='Francisco Morazán', max_length=500, null=True, verbose_name='Departamento #2')),
                ('locations', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección Detallada #2')),
                ('Departmentt', models.CharField(blank=True, choices=[('Atlántida', 'Atlántida'), ('Colón', 'Colón'), ('Comayagua', 'Comayagua'), ('Copán', 'Copán'), ('Cortés', 'Cortés'), ('Choluteca', 'Choluteca'), ('El Paraíso', 'El Paraíso'), ('Francisco Morazán', 'Francisco Morazán'), ('Gracias a Dios', 'Gracias a Dios'), ('Intibucá', 'Intibucá'), ('Islas de la Bahía', 'Islas de la Bahía'), ('La Paz', 'La Paz'), ('Lempira', 'Lempira'), ('Ocotepeque', 'Ocotepeque'), ('Olancho', 'Olancho'), ('Santa Bárbara', 'Santa Bárbara'), ('Valle', 'Valle'), ('Yoro', 'Yoro')], default='Francisco Morazán', max_length=500, null=True, verbose_name='Departamento #3')),
                ('locationt', models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección Detallada #3')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Nombre Empresa')),
                ('logo', models.ImageField(blank=True, upload_to='Company', verbose_name='Logo')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('resume', models.TextField(blank=True, verbose_name='Descripción Empresa')),
                ('plan', models.TextField(blank=True, choices=[('Comprador', 'Comprador'), ('Vendedor', 'Vendedor'), ('Empresario', 'Empresario'), ('Franquiciador', 'Franquiciador')], default='Comprador', max_length=50, verbose_name='Plan')),
                ('points', models.IntegerField(blank=True, default=0, null=True, verbose_name='Puntos')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Codigo de Registro')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
