# Generated by Django 3.0.5 on 2020-05-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0002_auto_20200508_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Sitio Web'),
        ),
    ]
