# Generated by Django 3.0.5 on 2020-05-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0003_auto_20200508_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
    ]
