# Generated by Django 3.0.5 on 2020-05-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0004_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Puntos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.TextField(blank=True, choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], max_length=500, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.BooleanField(blank=True, choices=[('Vendedor', 'Vendedor'), ('Empresario', 'Empresario'), ('Franquiciador', 'Franquiciador')], default='Vendedor', max_length=500, null=True, verbose_name='Plan'),
        ),
    ]
