# Generated by Django 3.0.5 on 2020-05-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0005_auto_20200513_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.BooleanField(blank=True, choices=[('v', 'Vendedor'), ('e', 'Empresario'), ('f', 'Franquiciador')], default='v', max_length=100, null=True, verbose_name='Plan'),
        ),
    ]
