# Generated by Django 3.0.5 on 2020-05-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0009_auto_20200514_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plan',
            field=models.TextField(blank=True, choices=[('Comprador', 'Comprador'), ('Vendedor', 'Vendedor'), ('Empresario', 'Empresario'), ('Franquiciador', 'Franquiciador')], default='Comprador', max_length=50, verbose_name='Plan'),
        ),
    ]
