# Generated by Django 3.0.5 on 2020-09-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0011_profile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='locations',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección #2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='locationt',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección #3'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Dirección #1'),
        ),
    ]
