# Generated by Django 3.0.5 on 2020-09-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useradmin', '0015_auto_20200912_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Department',
            field=models.CharField(blank=True, choices=[('Atlántida', 'Atlántida'), ('Colón', 'Colón'), ('Comayagua', 'Comayagua'), ('Copán', 'Copán'), ('Cortés', 'Cortés'), ('Choluteca', 'Choluteca'), ('El Paraíso', 'El Paraíso'), ('Francisco Morazán', 'Francisco Morazán'), ('Gracias a Dios', 'Gracias a Dios'), ('Intibucá', 'Intibucá'), ('Islas de la Bahía', 'Islas de la Bahía'), ('La Paz', 'La Paz'), ('Lempira', 'Lempira'), ('Ocotepeque', 'Ocotepeque'), ('Olancho', 'Olancho'), ('Santa Bárbara', 'Santa Bárbara'), ('Valle', 'Valle'), ('Yoro', 'Yoro')], default='Francisco Morazán', max_length=500, null=True, verbose_name='Departamento #1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Departments',
            field=models.CharField(blank=True, choices=[('Atlántida', 'Atlántida'), ('Colón', 'Colón'), ('Comayagua', 'Comayagua'), ('Copán', 'Copán'), ('Cortés', 'Cortés'), ('Choluteca', 'Choluteca'), ('El Paraíso', 'El Paraíso'), ('Francisco Morazán', 'Francisco Morazán'), ('Gracias a Dios', 'Gracias a Dios'), ('Intibucá', 'Intibucá'), ('Islas de la Bahía', 'Islas de la Bahía'), ('La Paz', 'La Paz'), ('Lempira', 'Lempira'), ('Ocotepeque', 'Ocotepeque'), ('Olancho', 'Olancho'), ('Santa Bárbara', 'Santa Bárbara'), ('Valle', 'Valle'), ('Yoro', 'Yoro')], default='Francisco Morazán', max_length=500, null=True, verbose_name='Departamento #2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Departmentt',
            field=models.CharField(blank=True, choices=[('Atlántida', 'Atlántida'), ('Colón', 'Colón'), ('Comayagua', 'Comayagua'), ('Copán', 'Copán'), ('Cortés', 'Cortés'), ('Choluteca', 'Choluteca'), ('El Paraíso', 'El Paraíso'), ('Francisco Morazán', 'Francisco Morazán'), ('Gracias a Dios', 'Gracias a Dios'), ('Intibucá', 'Intibucá'), ('Islas de la Bahía', 'Islas de la Bahía'), ('La Paz', 'La Paz'), ('Lempira', 'Lempira'), ('Ocotepeque', 'Ocotepeque'), ('Olancho', 'Olancho'), ('Santa Bárbara', 'Santa Bárbara'), ('Valle', 'Valle'), ('Yoro', 'Yoro')], default='Francisco Morazán', max_length=500, null=True, verbose_name='Departamento #3'),
        ),
    ]
